import { styles as all } from './styles';

// 모든 모달 공용 (헤더/입력/세그먼트/앨범상세/갤러리 픽커)
export const modalStyles = {
  modalHeaderContainer: all.modalHeaderContainer,
  inputGroup: all.inputGroup,
  appleLabel: all.appleLabel,
  appleInput: all.appleInput,
  appleSelector: all.appleSelector,
  appleSelectorText: all.appleSelectorText,
  addressSearchBoxContainer: all.addressSearchBoxContainer,
  addressSearchInputInside: all.addressSearchInputInside,
  addressSearchItemRow: all.addressSearchItemRow,
  addressSearchItemText: all.addressSearchItemText,
  addressSearchNoResult: all.addressSearchNoResult,
  dogAvatarUploadTrigger: all.dogAvatarUploadTrigger,
  avatarEditBadgeSmallAbsolute: all.avatarEditBadgeSmallAbsolute,
  appleGenderSegmentRow: all.appleGenderSegmentRow,
  appleSegmentButton: all.appleSegmentButton,
  appleSegmentButtonActive: all.appleSegmentButtonActive,
  appleSegmentButtonText: all.appleSegmentButtonText,
  appleSegmentButtonTextActive: all.appleSegmentButtonTextActive,
  galleryPickerCardTrigger: all.galleryPickerCardTrigger,
  galleryPickerCenterContainer: all.galleryPickerCenterContainer,
  galleryPickerTriggerText: all.galleryPickerTriggerText,
  galleryPreviewImageReal: all.galleryPreviewImageReal,
  albumDetailOverlayContainer: all.albumDetailOverlayContainer,
  albumDetailCentralCard: all.albumDetailCentralCard,
  detailCardPolaroidTopFrame: all.detailCardPolaroidTopFrame,
  albumDetailImageReal: all.albumDetailImageReal,
  detailCardTextContainer: all.detailCardTextContainer,
  detailCardDateHeader: all.detailCardDateHeader,
  albumDetailEditableMemoInput: all.albumDetailEditableMemoInput,
  detailActionButtonsRow: all.detailActionButtonsRow,
  detailActionBtn: all.detailActionBtn,
};
