import { styles as all } from './styles';

// Profile 화면 본문 (헤더/카드/반려견 카드/앨범 그리드)
export const profileStyles = {
  appleContainer: all.appleContainer,
  instaProfileHeaderCard: all.instaProfileHeaderCard,
  instaHeaderTopRow: all.instaHeaderTopRow,
  instaStatsContainer: all.instaStatsContainer,
  instaStatItem: all.instaStatItem,
  instaStatNumber: all.instaStatNumber,
  instaStatLabel: all.instaStatLabel,
  instaProfileBioWrapper: all.instaProfileBioWrapper,
  avatarWrapper: all.avatarWrapper,
  avatarPlaceholder: all.avatarPlaceholder,
  avatarImageReal: all.avatarImageReal,
  avatarIconText: all.avatarIconText,
  avatarEditBadge: all.avatarEditBadge,
  avatarEditBadgeText: all.avatarEditBadgeText,
  userHeadline: all.userHeadline,
  userSubline: all.userSubline,
  appleSecondaryButton: all.appleSecondaryButton,
  appleSecondaryButtonText: all.appleSecondaryButtonText,
  appleCardSection: all.appleCardSection,
  appleSectionTitle: all.appleSectionTitle,
  appleEmptyBox: all.appleEmptyBox,
  appleEmptyText: all.appleEmptyText,
  jobsAddInlineButton: all.jobsAddInlineButton,
  jobsAddInlineButtonText: all.jobsAddInlineButtonText,
  appleDogCard: all.appleDogCard,
  appleDogCardLeft: all.appleDogCardLeft,
  dogAvatarSmall: all.dogAvatarSmall,
  appleDogInfoWrapper: all.appleDogInfoWrapper,
  appleDogName: all.appleDogName,
  appleGenderTag: all.appleGenderTag,
  appleGenderTagText: all.appleGenderTagText,
  appleDogMetaData: all.appleDogMetaData,
  appleDogTendency: all.appleDogTendency,
  appleAgeBadge: all.appleAgeBadge,
  appleAgeBadgeText: all.appleAgeBadgeText,
  listItemRow: all.listItemRow,
  listAvatarPlaceholder: all.listAvatarPlaceholder,
  listItemTitle: all.listItemTitle,
  listItemSub: all.listItemSub,
  listActionButton: all.listActionButton,
  listActionButtonText: all.listActionButtonText,
  galleryGridContainer: all.galleryGridContainer,
  polaroidFrameSquare: all.polaroidFrameSquare,
  polaroidFrameSquareSelected: all.polaroidFrameSquareSelected,
  polaroidImageWrapper: all.polaroidImageWrapper,
  galleryImage: all.galleryImage,
  polaroidBottomArea: all.polaroidBottomArea,
  polaroidMemoSnippet: all.polaroidMemoSnippet,
  polaroidDateText: all.polaroidDateText,
  photoCheckboxCircle: all.photoCheckboxCircle,
  photoCheckboxCircleChecked: all.photoCheckboxCircleChecked,
  deleteActionBarButton: all.deleteActionBarButton,
  deleteActionBarButtonText: all.deleteActionBarButtonText,
};
