import { StyleSheet, Platform, Dimensions } from 'react-native';

export const { width } = Dimensions.get('window');

// ─────────────────────────────────────────────
// Design Tokens — Steve Jobs / Apple HIG 철학
// ─────────────────────────────────────────────
export const T = {
  // Colors
  accent:   '#FF8C00',   // 브랜드 오렌지
  blue:     '#007AFF',
  green:    '#30D158',
  red:      '#FF3B30',
  yellow:   '#FFD60A',
  // Neutrals
  label1:   '#1C1C1E',
  label2:   '#3A3A3C',
  label3:   '#636366',
  label4:   '#8E8E93',
  fill1:    '#F2F2F7',
  fill2:    '#E5E5EA',
  fill3:    '#D1D1D6',
  white:    '#FFFFFF',
  // Radius
  r8:  8,
  r12: 12,
  r16: 16,
  r20: 20,
  r24: 24,
  // Shadow
  shadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  shadowMd: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 5,
  },
};

export const styles = StyleSheet.create({
  // ── Layout
  container: { flex: 1, backgroundColor: '#000' },
  map: { width: '100%', height: '100%' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: T.fill1 },
  placeholderTabText: { fontSize: 15, color: T.label4, fontWeight: '600' },

  // ── Auth Screen (스티브 잡스 미니멀)
  authContainer: {
    flex: 1,
    backgroundColor: T.white,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  authLogoWrapper: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: T.accent,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
    ...T.shadowMd,
  },
  authLogoText: { fontSize: 38 },
  authTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: T.label1,
    marginBottom: 6,
    letterSpacing: -0.8,
  },
  authSubTitle: {
    fontSize: 15,
    fontWeight: '400',
    color: T.label4,
    marginBottom: 40,
    textAlign: 'center',
    lineHeight: 22,
  },
  authInput: {
    width: '100%',
    height: 52,
    backgroundColor: T.fill1,
    borderRadius: T.r12,
    paddingHorizontal: 16,
    fontSize: 16,
    color: T.label1,
    marginBottom: 12,
    fontWeight: '400',
  },
  authButton: {
    width: '100%',
    height: 54,
    backgroundColor: T.accent,
    borderRadius: T.r16,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    ...T.shadowMd,
    shadowColor: T.accent,
    shadowOpacity: 0.35,
  },
  authButtonText: { color: T.white, fontSize: 17, fontWeight: '600', letterSpacing: -0.3 },
  authDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
    width: '100%',
  },
  authDividerLine: { flex: 1, height: 1, backgroundColor: T.fill2 },
  authDividerText: { marginHorizontal: 12, fontSize: 13, color: T.label4, fontWeight: '500' },
  authSocialButton: {
    width: '100%',
    height: 52,
    borderRadius: T.r16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: T.fill2,
    backgroundColor: T.white,
  },
  authSocialIcon: { fontSize: 20, marginRight: 10 },
  authSocialText: { fontSize: 16, fontWeight: '500', color: T.label1 },
  authKakaoButton: {
    backgroundColor: '#FEE500',
    borderColor: '#FEE500',
  },
  authGoogleButton: {
    backgroundColor: T.white,
    borderColor: T.fill2,
  },
  authToggleText: { color: T.accent, fontSize: 14, fontWeight: '600', marginTop: 20 },

  // ── Map POI / Match markers
  poiMarkerContainer: {
    backgroundColor: T.white,
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    ...T.shadow,
  },
  poiMarkerIcon: { fontSize: 18 },
  matchMarkerContainer: { alignItems: 'center', justifyContent: 'center' },
  matchMarkerText: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    color: T.label1,
    fontSize: 10,
    fontWeight: '700',
    paddingVertical: 3,
    paddingHorizontal: 7,
    borderRadius: 10,
    overflow: 'hidden',
    zIndex: 2,
    ...T.shadow,
  },
  matchMarkerChoco: {
    backgroundColor: T.blue,
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 3,
    borderColor: T.white,
    justifyContent: 'center',
    alignItems: 'center',
    ...T.shadow,
    marginTop: -10,
    zIndex: 1,
  },

  // ── Map Search Bar
  searchBarFloatingContainer: {
    position: 'absolute',
    left: 15,
    right: 15,
    backgroundColor: 'rgba(255,255,255,0.97)',
    borderRadius: T.r16,
    ...T.shadowMd,
    zIndex: 11,
  },
  searchBarWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    height: 50,
  },
  vectorSearchIconWrapper: {
    width: 20,
    height: 20,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.4,
  },
  vectorSearchCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#000',
    position: 'absolute',
    top: 2,
    left: 2,
  },
  vectorSearchLine: {
    width: 2,
    height: 7,
    backgroundColor: '#000',
    position: 'absolute',
    bottom: 2,
    right: 3,
    transform: [{ rotate: '-45deg' }],
  },
  searchInput: { flex: 1, fontSize: 15, color: T.label1, fontWeight: '400', paddingVertical: 0 },

  // ── Map nearby badge (분리된 주변 강아지 표시창)
  nearbyBadgeContainer: {
    position: 'absolute',
    left: 15,
    right: 15,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: T.r12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    ...T.shadow,
    zIndex: 11,
  },
  nearbyBadgeIcon: { fontSize: 16, marginRight: 8 },
  nearbyBadgeText: { fontSize: 13, color: T.label3, fontWeight: '500', flex: 1 },

  // ── Dashboard Card (산책모드)
  dashboardCard: {
    position: 'absolute',
    left: 15,
    right: 15,
    borderRadius: T.r20,
    ...T.shadowMd,
    zIndex: 10,
  },
  dashboardRow: { flexDirection: 'row', justifyContent: 'space-around', paddingVertical: 18 },
  dashboardItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  dashboardValue: { fontWeight: '700', fontSize: 26, letterSpacing: -0.5 },
  dashboardLabel: { fontSize: 11, fontWeight: '600', letterSpacing: -0.1 },
  paceContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  paceDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 5,
    shadowRadius: 2,
    shadowOpacity: 0.5,
    elevation: 2,
    shadowColor: Platform.OS === 'ios' ? '#fff' : '#000',
  },

  // ── Walk Timer
  walkTimerContainer: {
    position: 'absolute',
    left: 15,
    right: 15,
    alignItems: 'center',
    zIndex: 10,
  },
  walkTimerText: {
    fontSize: 13,
    fontWeight: '600',
    color: T.green,
    letterSpacing: 1,
  },

  // ── My Location Button
  myLocationFloatingContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 190 : 140,
    right: 15,
    width: 48,
    height: 48,
    borderRadius: T.r16,
    overflow: 'hidden',
    ...T.shadowMd,
    zIndex: 10,
  },
  myLocationButton_apple: { width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center' },
  arrowIcon_apple: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderBottomWidth: 16,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    transform: [{ rotate: '45deg' }],
    marginRight: 2,
    marginTop: -2,
  },

  // ── Weather Widget
  weatherWidgetContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 250 : 200,
    right: 15,
    width: 48,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: T.r16,
    paddingVertical: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
    ...T.shadowMd,
    zIndex: 10,
  },
  weatherIcon: { fontSize: 20, marginBottom: 2 },
  weatherTemp: { fontSize: 11, fontWeight: '700', color: T.label1, textAlign: 'center' },
  weatherDesc: { fontSize: 9, color: T.label4, fontWeight: '600', textAlign: 'center' },

  // ── Floating Button Panel
  floatingButtonPanel: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 100 : 90,
    left: 15,
    right: 15,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    height: 65,
    zIndex: 10,
  },
  actionControlsWrapper: { flexDirection: 'row', alignItems: 'center', width: '100%' },
  walkingStatusBadge: {
    backgroundColor: '#1C1C1E',
    borderRadius: T.r16,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  startButton: {
    backgroundColor: T.accent,
    paddingVertical: 16,
    borderRadius: T.r16,
    alignItems: 'center',
    shadowColor: T.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  startButtonText: { color: T.white, fontSize: 16, fontWeight: '700', letterSpacing: -0.3 },
  stopButton: { width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center' },
  stopButtonText: { color: T.red, fontSize: 15, fontWeight: '700', letterSpacing: -0.2 },

  // ── Profile Container
  appleContainer: {
    flex: 1,
    backgroundColor: T.fill1,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 60 : 30,
  },

  // ── Profile Header Card
  instaProfileHeaderCard: {
    backgroundColor: T.white,
    borderRadius: T.r24,
    padding: 20,
    marginTop: 15,
    marginBottom: 16,
    ...T.shadow,
  },
  instaHeaderTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  instaStatsContainer: { flexDirection: 'row', flex: 1, justifyContent: 'space-around', marginLeft: 20 },
  instaStatItem: { alignItems: 'center', paddingVertical: 6, paddingHorizontal: 10 },
  instaStatNumber: { fontSize: 20, fontWeight: '700', color: T.label1, letterSpacing: -0.5 },
  instaStatLabel: { fontSize: 12, color: T.label4, fontWeight: '600', marginTop: 2 },
  instaProfileBioWrapper: { marginTop: 16, paddingHorizontal: 4 },

  // ── Avatar (+ 배지 제거됨)
  avatarWrapper: { position: 'relative' },
  avatarPlaceholder: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: T.fill2,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarImageReal: { width: '100%', height: '100%', borderRadius: 42 },
  avatarIconText: { fontSize: 34 },
  // avatarEditBadge 제거 (요구사항 1)
  avatarEditBadge: { display: 'none', width: 0, height: 0 },
  avatarEditBadgeText: { display: 'none' },

  userHeadline: { fontSize: 21, fontWeight: '700', color: T.label1, letterSpacing: -0.5 },
  userSubline: { fontSize: 13, color: T.label3, fontWeight: '400', marginTop: 4 },

  // ── Buttons
  appleSecondaryButton: {
    marginTop: 16,
    paddingVertical: 10,
    borderRadius: T.r12,
    backgroundColor: T.fill1,
    alignItems: 'center',
  },
  appleSecondaryButtonText: { color: T.red, fontSize: 14, fontWeight: '600' },

  // ── Card Section
  appleCardSection: {
    backgroundColor: T.white,
    borderRadius: T.r24,
    padding: 20,
    marginBottom: 16,
    ...T.shadow,
  },
  appleSectionTitle: { fontSize: 18, fontWeight: '700', color: T.label1, marginBottom: 16, letterSpacing: -0.3 },
  appleEmptyBox: { paddingVertical: 30, alignItems: 'center' },
  appleEmptyText: { fontSize: 13, color: T.label4, textAlign: 'center', lineHeight: 20 },

  jobsAddInlineButton: { backgroundColor: T.fill1, paddingHorizontal: 14, paddingVertical: 7, borderRadius: 10 },
  jobsAddInlineButtonText: { color: T.blue, fontSize: 13, fontWeight: '700' },

  // ── Dog Card
  appleDogCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: T.fill1,
  },
  appleDogCardLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  dogAvatarSmall: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: T.fill1,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
    overflow: 'hidden',
  },
  appleDogInfoWrapper: { flex: 1 },
  appleDogName: { fontSize: 16, fontWeight: '700', color: T.label1 },
  appleGenderTag: {
    marginLeft: 6,
    backgroundColor: T.fill2,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  appleGenderTagText: { fontSize: 10, fontWeight: '700', color: T.label2 },
  appleDogMetaData: { fontSize: 13, color: T.label4, marginTop: 3, fontWeight: '400' },
  appleDogTendency: { fontSize: 12, color: T.label3, marginTop: 4, fontStyle: 'italic' },

  appleAgeBadge: { backgroundColor: T.fill1, paddingHorizontal: 12, paddingVertical: 6, borderRadius: T.r12 },
  appleAgeBadgeText: { fontSize: 12, fontWeight: '700', color: T.label1, letterSpacing: -0.2 },

  // ── List Item
  listItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: T.fill1,
  },
  listAvatarPlaceholder: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: T.fill2,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  listItemTitle: { fontSize: 15, fontWeight: '700', color: T.label1 },
  listItemSub: { fontSize: 12, color: T.label4, marginTop: 2 },
  listActionButton: { backgroundColor: T.fill1, paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8 },
  listActionButtonText: { fontSize: 12, fontWeight: '700', color: T.blue },

  // ── Gallery
  galleryGridContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  polaroidFrameSquare: {
    width: (width - 84) / 2,
    backgroundColor: T.white,
    borderRadius: 4,
    padding: 10,
    marginBottom: 16,
    ...T.shadow,
    borderWidth: 1,
    borderColor: '#EAEAEA',
  },
  polaroidFrameSquareSelected: { borderColor: T.red, borderWidth: 2, backgroundColor: '#FFF5F5' },
  polaroidImageWrapper: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: T.fill1,
    borderRadius: 2,
    overflow: 'hidden',
    position: 'relative',
  },
  galleryImage: { width: '100%', height: '100%' },
  polaroidBottomArea: { marginTop: 10, alignItems: 'center', paddingHorizontal: 2 },
  polaroidMemoSnippet: { fontSize: 12, fontWeight: '600', color: T.label2, textAlign: 'center' },
  polaroidDateText: { fontSize: 10, color: '#A9A9A9', marginTop: 4, fontWeight: '400', letterSpacing: 0.2 },

  photoCheckboxCircle: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderWidth: 1.5,
    borderColor: T.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoCheckboxCircleChecked: { backgroundColor: T.red, borderColor: T.red },
  deleteActionBarButton: {
    backgroundColor: T.red,
    borderRadius: T.r16,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: T.red,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  deleteActionBarButtonText: { color: T.white, fontSize: 14, fontWeight: '700' },

  galleryPickerCardTrigger: {
    width: '100%',
    height: 180,
    backgroundColor: T.fill1,
    borderRadius: T.r16,
    borderStyle: 'dashed',
    borderWidth: 1.5,
    borderColor: T.fill3,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    marginTop: 4,
  },
  galleryPickerCenterContainer: { alignItems: 'center', paddingHorizontal: 20 },
  galleryPickerTriggerText: {
    fontSize: 13,
    color: T.label3,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 18,
  },
  galleryPreviewImageReal: { width: '100%', height: '100%', borderRadius: T.r16 },

  // ── Album Detail
  albumDetailOverlayContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  albumDetailCentralCard: {
    width: '100%',
    backgroundColor: T.white,
    borderRadius: T.r20,
    padding: 16,
    ...T.shadowMd,
  },
  detailCardPolaroidTopFrame: {
    width: '100%',
    aspectRatio: 1.05,
    backgroundColor: '#F9F9F9',
    borderWidth: 1,
    borderColor: T.fill2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  albumDetailImageReal: { width: '100%', height: '100%' },
  detailCardTextContainer: { marginTop: 16 },
  detailCardDateHeader: { fontSize: 12, color: T.label4, fontWeight: '600', marginBottom: 12 },
  albumDetailEditableMemoInput: {
    width: '100%',
    backgroundColor: T.fill1,
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: T.label1,
    fontWeight: '400',
    minHeight: 75,
    textAlignVertical: 'top',
    marginBottom: 16,
  },
  detailActionButtonsRow: { flexDirection: 'row', justifyContent: 'space-between' },
  detailActionBtn: { flex: 1, height: 44, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginHorizontal: 4 },

  // ── Modal Header
  modalHeaderContainer: {
    height: 56,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: T.fill1,
    backgroundColor: T.white,
  },

  // ── Form
  inputGroup: { marginBottom: 14 },
  appleLabel: { fontSize: 13, fontWeight: '600', color: T.label1, marginBottom: 6, paddingLeft: 2 },
  appleInput: {
    width: '100%',
    height: 44,
    backgroundColor: T.fill1,
    borderRadius: 10,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#000',
    fontWeight: '400',
  },
  appleSelector: {
    width: '100%',
    height: 44,
    backgroundColor: T.fill1,
    borderRadius: 10,
    paddingHorizontal: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appleSelectorText: { fontSize: 14, color: T.label1, fontWeight: '400' },

  // ── Address Search
  addressSearchBoxContainer: {
    backgroundColor: T.fill1,
    borderRadius: T.r12,
    marginTop: 6,
    padding: 10,
    borderWidth: 1,
    borderColor: T.fill2,
  },
  addressSearchInputInside: {
    height: 40,
    backgroundColor: T.white,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 13,
    color: '#000',
    marginBottom: 8,
    fontWeight: '600',
  },
  addressSearchItemRow: { paddingVertical: 12, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: T.fill2 },
  addressSearchItemText: { fontSize: 13, color: T.label1, fontWeight: '400' },
  addressSearchNoResult: { paddingVertical: 14, fontSize: 12, color: T.label4, textAlign: 'center' },

  // ── Dog Avatar Upload
  dogAvatarUploadTrigger: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: T.fill1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'visible',
    borderWidth: 1,
    borderColor: T.fill2,
  },
  avatarEditBadgeSmallAbsolute: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: T.blue,
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: T.white,
  },

  // ── Segment Control
  appleGenderSegmentRow: {
    flexDirection: 'row',
    backgroundColor: T.fill2,
    borderRadius: 10,
    padding: 2,
    justifyContent: 'space-between',
  },
  appleSegmentButton: {
    flex: 1,
    paddingVertical: 8,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  appleSegmentButtonActive: {
    backgroundColor: T.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  appleSegmentButtonText: { fontSize: 11, fontWeight: '600', color: T.label3 },
  appleSegmentButtonTextActive: { color: T.label1, fontWeight: '700' },
});
